//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assisgment_Desk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Taskid { get; set; }
        public string Title { get; set; }
        public string Descriptionn { get; set; }
        public string Statuss { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> Userid { get; set; }
    
        public virtual Userr Userr { get; set; }
    }
}
